# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/100/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/100/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/krusto/CLionProjects/OpenglTest

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/krusto/CLionProjects/OpenglTest

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/100/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/100/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/krusto/CLionProjects/OpenglTest/CMakeFiles /home/krusto/CLionProjects/OpenglTest/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/krusto/CLionProjects/OpenglTest/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OpenglTest

# Build rule for target.
OpenglTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OpenglTest
.PHONY : OpenglTest

# fast build rule for target.
OpenglTest/fast:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/build
.PHONY : OpenglTest/fast

Dependencies/ImGUI/imgui.o: Dependencies/ImGUI/imgui.cpp.o

.PHONY : Dependencies/ImGUI/imgui.o

# target to build an object file
Dependencies/ImGUI/imgui.cpp.o:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/Dependencies/ImGUI/imgui.cpp.o
.PHONY : Dependencies/ImGUI/imgui.cpp.o

Dependencies/ImGUI/imgui.i: Dependencies/ImGUI/imgui.cpp.i

.PHONY : Dependencies/ImGUI/imgui.i

# target to preprocess a source file
Dependencies/ImGUI/imgui.cpp.i:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/Dependencies/ImGUI/imgui.cpp.i
.PHONY : Dependencies/ImGUI/imgui.cpp.i

Dependencies/ImGUI/imgui.s: Dependencies/ImGUI/imgui.cpp.s

.PHONY : Dependencies/ImGUI/imgui.s

# target to generate assembly for a file
Dependencies/ImGUI/imgui.cpp.s:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/Dependencies/ImGUI/imgui.cpp.s
.PHONY : Dependencies/ImGUI/imgui.cpp.s

Dependencies/ImGUI/imgui_demo.o: Dependencies/ImGUI/imgui_demo.cpp.o

.PHONY : Dependencies/ImGUI/imgui_demo.o

# target to build an object file
Dependencies/ImGUI/imgui_demo.cpp.o:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/Dependencies/ImGUI/imgui_demo.cpp.o
.PHONY : Dependencies/ImGUI/imgui_demo.cpp.o

Dependencies/ImGUI/imgui_demo.i: Dependencies/ImGUI/imgui_demo.cpp.i

.PHONY : Dependencies/ImGUI/imgui_demo.i

# target to preprocess a source file
Dependencies/ImGUI/imgui_demo.cpp.i:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/Dependencies/ImGUI/imgui_demo.cpp.i
.PHONY : Dependencies/ImGUI/imgui_demo.cpp.i

Dependencies/ImGUI/imgui_demo.s: Dependencies/ImGUI/imgui_demo.cpp.s

.PHONY : Dependencies/ImGUI/imgui_demo.s

# target to generate assembly for a file
Dependencies/ImGUI/imgui_demo.cpp.s:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/Dependencies/ImGUI/imgui_demo.cpp.s
.PHONY : Dependencies/ImGUI/imgui_demo.cpp.s

Dependencies/ImGUI/imgui_draw.o: Dependencies/ImGUI/imgui_draw.cpp.o

.PHONY : Dependencies/ImGUI/imgui_draw.o

# target to build an object file
Dependencies/ImGUI/imgui_draw.cpp.o:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/Dependencies/ImGUI/imgui_draw.cpp.o
.PHONY : Dependencies/ImGUI/imgui_draw.cpp.o

Dependencies/ImGUI/imgui_draw.i: Dependencies/ImGUI/imgui_draw.cpp.i

.PHONY : Dependencies/ImGUI/imgui_draw.i

# target to preprocess a source file
Dependencies/ImGUI/imgui_draw.cpp.i:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/Dependencies/ImGUI/imgui_draw.cpp.i
.PHONY : Dependencies/ImGUI/imgui_draw.cpp.i

Dependencies/ImGUI/imgui_draw.s: Dependencies/ImGUI/imgui_draw.cpp.s

.PHONY : Dependencies/ImGUI/imgui_draw.s

# target to generate assembly for a file
Dependencies/ImGUI/imgui_draw.cpp.s:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/Dependencies/ImGUI/imgui_draw.cpp.s
.PHONY : Dependencies/ImGUI/imgui_draw.cpp.s

Dependencies/ImGUI/imgui_impl_glfw.o: Dependencies/ImGUI/imgui_impl_glfw.cpp.o

.PHONY : Dependencies/ImGUI/imgui_impl_glfw.o

# target to build an object file
Dependencies/ImGUI/imgui_impl_glfw.cpp.o:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/Dependencies/ImGUI/imgui_impl_glfw.cpp.o
.PHONY : Dependencies/ImGUI/imgui_impl_glfw.cpp.o

Dependencies/ImGUI/imgui_impl_glfw.i: Dependencies/ImGUI/imgui_impl_glfw.cpp.i

.PHONY : Dependencies/ImGUI/imgui_impl_glfw.i

# target to preprocess a source file
Dependencies/ImGUI/imgui_impl_glfw.cpp.i:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/Dependencies/ImGUI/imgui_impl_glfw.cpp.i
.PHONY : Dependencies/ImGUI/imgui_impl_glfw.cpp.i

Dependencies/ImGUI/imgui_impl_glfw.s: Dependencies/ImGUI/imgui_impl_glfw.cpp.s

.PHONY : Dependencies/ImGUI/imgui_impl_glfw.s

# target to generate assembly for a file
Dependencies/ImGUI/imgui_impl_glfw.cpp.s:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/Dependencies/ImGUI/imgui_impl_glfw.cpp.s
.PHONY : Dependencies/ImGUI/imgui_impl_glfw.cpp.s

Dependencies/ImGUI/imgui_impl_opengl3.o: Dependencies/ImGUI/imgui_impl_opengl3.cpp.o

.PHONY : Dependencies/ImGUI/imgui_impl_opengl3.o

# target to build an object file
Dependencies/ImGUI/imgui_impl_opengl3.cpp.o:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/Dependencies/ImGUI/imgui_impl_opengl3.cpp.o
.PHONY : Dependencies/ImGUI/imgui_impl_opengl3.cpp.o

Dependencies/ImGUI/imgui_impl_opengl3.i: Dependencies/ImGUI/imgui_impl_opengl3.cpp.i

.PHONY : Dependencies/ImGUI/imgui_impl_opengl3.i

# target to preprocess a source file
Dependencies/ImGUI/imgui_impl_opengl3.cpp.i:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/Dependencies/ImGUI/imgui_impl_opengl3.cpp.i
.PHONY : Dependencies/ImGUI/imgui_impl_opengl3.cpp.i

Dependencies/ImGUI/imgui_impl_opengl3.s: Dependencies/ImGUI/imgui_impl_opengl3.cpp.s

.PHONY : Dependencies/ImGUI/imgui_impl_opengl3.s

# target to generate assembly for a file
Dependencies/ImGUI/imgui_impl_opengl3.cpp.s:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/Dependencies/ImGUI/imgui_impl_opengl3.cpp.s
.PHONY : Dependencies/ImGUI/imgui_impl_opengl3.cpp.s

Dependencies/ImGUI/imgui_widgets.o: Dependencies/ImGUI/imgui_widgets.cpp.o

.PHONY : Dependencies/ImGUI/imgui_widgets.o

# target to build an object file
Dependencies/ImGUI/imgui_widgets.cpp.o:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/Dependencies/ImGUI/imgui_widgets.cpp.o
.PHONY : Dependencies/ImGUI/imgui_widgets.cpp.o

Dependencies/ImGUI/imgui_widgets.i: Dependencies/ImGUI/imgui_widgets.cpp.i

.PHONY : Dependencies/ImGUI/imgui_widgets.i

# target to preprocess a source file
Dependencies/ImGUI/imgui_widgets.cpp.i:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/Dependencies/ImGUI/imgui_widgets.cpp.i
.PHONY : Dependencies/ImGUI/imgui_widgets.cpp.i

Dependencies/ImGUI/imgui_widgets.s: Dependencies/ImGUI/imgui_widgets.cpp.s

.PHONY : Dependencies/ImGUI/imgui_widgets.s

# target to generate assembly for a file
Dependencies/ImGUI/imgui_widgets.cpp.s:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/Dependencies/ImGUI/imgui_widgets.cpp.s
.PHONY : Dependencies/ImGUI/imgui_widgets.cpp.s

Dependencies/stb_image/stb_image.o: Dependencies/stb_image/stb_image.cpp.o

.PHONY : Dependencies/stb_image/stb_image.o

# target to build an object file
Dependencies/stb_image/stb_image.cpp.o:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/Dependencies/stb_image/stb_image.cpp.o
.PHONY : Dependencies/stb_image/stb_image.cpp.o

Dependencies/stb_image/stb_image.i: Dependencies/stb_image/stb_image.cpp.i

.PHONY : Dependencies/stb_image/stb_image.i

# target to preprocess a source file
Dependencies/stb_image/stb_image.cpp.i:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/Dependencies/stb_image/stb_image.cpp.i
.PHONY : Dependencies/stb_image/stb_image.cpp.i

Dependencies/stb_image/stb_image.s: Dependencies/stb_image/stb_image.cpp.s

.PHONY : Dependencies/stb_image/stb_image.s

# target to generate assembly for a file
Dependencies/stb_image/stb_image.cpp.s:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/Dependencies/stb_image/stb_image.cpp.s
.PHONY : Dependencies/stb_image/stb_image.cpp.s

OpenGLClasses/Camera.o: OpenGLClasses/Camera.cpp.o

.PHONY : OpenGLClasses/Camera.o

# target to build an object file
OpenGLClasses/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/Camera.cpp.o
.PHONY : OpenGLClasses/Camera.cpp.o

OpenGLClasses/Camera.i: OpenGLClasses/Camera.cpp.i

.PHONY : OpenGLClasses/Camera.i

# target to preprocess a source file
OpenGLClasses/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/Camera.cpp.i
.PHONY : OpenGLClasses/Camera.cpp.i

OpenGLClasses/Camera.s: OpenGLClasses/Camera.cpp.s

.PHONY : OpenGLClasses/Camera.s

# target to generate assembly for a file
OpenGLClasses/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/Camera.cpp.s
.PHONY : OpenGLClasses/Camera.cpp.s

OpenGLClasses/ColoredModel.o: OpenGLClasses/ColoredModel.cpp.o

.PHONY : OpenGLClasses/ColoredModel.o

# target to build an object file
OpenGLClasses/ColoredModel.cpp.o:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/ColoredModel.cpp.o
.PHONY : OpenGLClasses/ColoredModel.cpp.o

OpenGLClasses/ColoredModel.i: OpenGLClasses/ColoredModel.cpp.i

.PHONY : OpenGLClasses/ColoredModel.i

# target to preprocess a source file
OpenGLClasses/ColoredModel.cpp.i:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/ColoredModel.cpp.i
.PHONY : OpenGLClasses/ColoredModel.cpp.i

OpenGLClasses/ColoredModel.s: OpenGLClasses/ColoredModel.cpp.s

.PHONY : OpenGLClasses/ColoredModel.s

# target to generate assembly for a file
OpenGLClasses/ColoredModel.cpp.s:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/ColoredModel.cpp.s
.PHONY : OpenGLClasses/ColoredModel.cpp.s

OpenGLClasses/Entity.o: OpenGLClasses/Entity.cpp.o

.PHONY : OpenGLClasses/Entity.o

# target to build an object file
OpenGLClasses/Entity.cpp.o:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/Entity.cpp.o
.PHONY : OpenGLClasses/Entity.cpp.o

OpenGLClasses/Entity.i: OpenGLClasses/Entity.cpp.i

.PHONY : OpenGLClasses/Entity.i

# target to preprocess a source file
OpenGLClasses/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/Entity.cpp.i
.PHONY : OpenGLClasses/Entity.cpp.i

OpenGLClasses/Entity.s: OpenGLClasses/Entity.cpp.s

.PHONY : OpenGLClasses/Entity.s

# target to generate assembly for a file
OpenGLClasses/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/Entity.cpp.s
.PHONY : OpenGLClasses/Entity.cpp.s

OpenGLClasses/LightSource.o: OpenGLClasses/LightSource.cpp.o

.PHONY : OpenGLClasses/LightSource.o

# target to build an object file
OpenGLClasses/LightSource.cpp.o:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/LightSource.cpp.o
.PHONY : OpenGLClasses/LightSource.cpp.o

OpenGLClasses/LightSource.i: OpenGLClasses/LightSource.cpp.i

.PHONY : OpenGLClasses/LightSource.i

# target to preprocess a source file
OpenGLClasses/LightSource.cpp.i:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/LightSource.cpp.i
.PHONY : OpenGLClasses/LightSource.cpp.i

OpenGLClasses/LightSource.s: OpenGLClasses/LightSource.cpp.s

.PHONY : OpenGLClasses/LightSource.s

# target to generate assembly for a file
OpenGLClasses/LightSource.cpp.s:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/LightSource.cpp.s
.PHONY : OpenGLClasses/LightSource.cpp.s

OpenGLClasses/RawModel.o: OpenGLClasses/RawModel.cpp.o

.PHONY : OpenGLClasses/RawModel.o

# target to build an object file
OpenGLClasses/RawModel.cpp.o:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/RawModel.cpp.o
.PHONY : OpenGLClasses/RawModel.cpp.o

OpenGLClasses/RawModel.i: OpenGLClasses/RawModel.cpp.i

.PHONY : OpenGLClasses/RawModel.i

# target to preprocess a source file
OpenGLClasses/RawModel.cpp.i:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/RawModel.cpp.i
.PHONY : OpenGLClasses/RawModel.cpp.i

OpenGLClasses/RawModel.s: OpenGLClasses/RawModel.cpp.s

.PHONY : OpenGLClasses/RawModel.s

# target to generate assembly for a file
OpenGLClasses/RawModel.cpp.s:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/RawModel.cpp.s
.PHONY : OpenGLClasses/RawModel.cpp.s

OpenGLClasses/Shader.o: OpenGLClasses/Shader.cpp.o

.PHONY : OpenGLClasses/Shader.o

# target to build an object file
OpenGLClasses/Shader.cpp.o:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/Shader.cpp.o
.PHONY : OpenGLClasses/Shader.cpp.o

OpenGLClasses/Shader.i: OpenGLClasses/Shader.cpp.i

.PHONY : OpenGLClasses/Shader.i

# target to preprocess a source file
OpenGLClasses/Shader.cpp.i:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/Shader.cpp.i
.PHONY : OpenGLClasses/Shader.cpp.i

OpenGLClasses/Shader.s: OpenGLClasses/Shader.cpp.s

.PHONY : OpenGLClasses/Shader.s

# target to generate assembly for a file
OpenGLClasses/Shader.cpp.s:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/Shader.cpp.s
.PHONY : OpenGLClasses/Shader.cpp.s

OpenGLClasses/ShaderManager.o: OpenGLClasses/ShaderManager.cpp.o

.PHONY : OpenGLClasses/ShaderManager.o

# target to build an object file
OpenGLClasses/ShaderManager.cpp.o:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/ShaderManager.cpp.o
.PHONY : OpenGLClasses/ShaderManager.cpp.o

OpenGLClasses/ShaderManager.i: OpenGLClasses/ShaderManager.cpp.i

.PHONY : OpenGLClasses/ShaderManager.i

# target to preprocess a source file
OpenGLClasses/ShaderManager.cpp.i:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/ShaderManager.cpp.i
.PHONY : OpenGLClasses/ShaderManager.cpp.i

OpenGLClasses/ShaderManager.s: OpenGLClasses/ShaderManager.cpp.s

.PHONY : OpenGLClasses/ShaderManager.s

# target to generate assembly for a file
OpenGLClasses/ShaderManager.cpp.s:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/ShaderManager.cpp.s
.PHONY : OpenGLClasses/ShaderManager.cpp.s

OpenGLClasses/Texture.o: OpenGLClasses/Texture.cpp.o

.PHONY : OpenGLClasses/Texture.o

# target to build an object file
OpenGLClasses/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/Texture.cpp.o
.PHONY : OpenGLClasses/Texture.cpp.o

OpenGLClasses/Texture.i: OpenGLClasses/Texture.cpp.i

.PHONY : OpenGLClasses/Texture.i

# target to preprocess a source file
OpenGLClasses/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/Texture.cpp.i
.PHONY : OpenGLClasses/Texture.cpp.i

OpenGLClasses/Texture.s: OpenGLClasses/Texture.cpp.s

.PHONY : OpenGLClasses/Texture.s

# target to generate assembly for a file
OpenGLClasses/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/Texture.cpp.s
.PHONY : OpenGLClasses/Texture.cpp.s

OpenGLClasses/TexturedModel.o: OpenGLClasses/TexturedModel.cpp.o

.PHONY : OpenGLClasses/TexturedModel.o

# target to build an object file
OpenGLClasses/TexturedModel.cpp.o:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/TexturedModel.cpp.o
.PHONY : OpenGLClasses/TexturedModel.cpp.o

OpenGLClasses/TexturedModel.i: OpenGLClasses/TexturedModel.cpp.i

.PHONY : OpenGLClasses/TexturedModel.i

# target to preprocess a source file
OpenGLClasses/TexturedModel.cpp.i:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/TexturedModel.cpp.i
.PHONY : OpenGLClasses/TexturedModel.cpp.i

OpenGLClasses/TexturedModel.s: OpenGLClasses/TexturedModel.cpp.s

.PHONY : OpenGLClasses/TexturedModel.s

# target to generate assembly for a file
OpenGLClasses/TexturedModel.cpp.s:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/TexturedModel.cpp.s
.PHONY : OpenGLClasses/TexturedModel.cpp.s

OpenGLClasses/Vertex.o: OpenGLClasses/Vertex.cpp.o

.PHONY : OpenGLClasses/Vertex.o

# target to build an object file
OpenGLClasses/Vertex.cpp.o:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/Vertex.cpp.o
.PHONY : OpenGLClasses/Vertex.cpp.o

OpenGLClasses/Vertex.i: OpenGLClasses/Vertex.cpp.i

.PHONY : OpenGLClasses/Vertex.i

# target to preprocess a source file
OpenGLClasses/Vertex.cpp.i:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/Vertex.cpp.i
.PHONY : OpenGLClasses/Vertex.cpp.i

OpenGLClasses/Vertex.s: OpenGLClasses/Vertex.cpp.s

.PHONY : OpenGLClasses/Vertex.s

# target to generate assembly for a file
OpenGLClasses/Vertex.cpp.s:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/OpenGLClasses/Vertex.cpp.s
.PHONY : OpenGLClasses/Vertex.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/main.cpp.s
.PHONY : main.cpp.s

obj_parser.o: obj_parser.cpp.o

.PHONY : obj_parser.o

# target to build an object file
obj_parser.cpp.o:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/obj_parser.cpp.o
.PHONY : obj_parser.cpp.o

obj_parser.i: obj_parser.cpp.i

.PHONY : obj_parser.i

# target to preprocess a source file
obj_parser.cpp.i:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/obj_parser.cpp.i
.PHONY : obj_parser.cpp.i

obj_parser.s: obj_parser.cpp.s

.PHONY : obj_parser.s

# target to generate assembly for a file
obj_parser.cpp.s:
	$(MAKE) -f CMakeFiles/OpenglTest.dir/build.make CMakeFiles/OpenglTest.dir/obj_parser.cpp.s
.PHONY : obj_parser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... OpenglTest"
	@echo "... edit_cache"
	@echo "... Dependencies/ImGUI/imgui.o"
	@echo "... Dependencies/ImGUI/imgui.i"
	@echo "... Dependencies/ImGUI/imgui.s"
	@echo "... Dependencies/ImGUI/imgui_demo.o"
	@echo "... Dependencies/ImGUI/imgui_demo.i"
	@echo "... Dependencies/ImGUI/imgui_demo.s"
	@echo "... Dependencies/ImGUI/imgui_draw.o"
	@echo "... Dependencies/ImGUI/imgui_draw.i"
	@echo "... Dependencies/ImGUI/imgui_draw.s"
	@echo "... Dependencies/ImGUI/imgui_impl_glfw.o"
	@echo "... Dependencies/ImGUI/imgui_impl_glfw.i"
	@echo "... Dependencies/ImGUI/imgui_impl_glfw.s"
	@echo "... Dependencies/ImGUI/imgui_impl_opengl3.o"
	@echo "... Dependencies/ImGUI/imgui_impl_opengl3.i"
	@echo "... Dependencies/ImGUI/imgui_impl_opengl3.s"
	@echo "... Dependencies/ImGUI/imgui_widgets.o"
	@echo "... Dependencies/ImGUI/imgui_widgets.i"
	@echo "... Dependencies/ImGUI/imgui_widgets.s"
	@echo "... Dependencies/stb_image/stb_image.o"
	@echo "... Dependencies/stb_image/stb_image.i"
	@echo "... Dependencies/stb_image/stb_image.s"
	@echo "... OpenGLClasses/Camera.o"
	@echo "... OpenGLClasses/Camera.i"
	@echo "... OpenGLClasses/Camera.s"
	@echo "... OpenGLClasses/ColoredModel.o"
	@echo "... OpenGLClasses/ColoredModel.i"
	@echo "... OpenGLClasses/ColoredModel.s"
	@echo "... OpenGLClasses/Entity.o"
	@echo "... OpenGLClasses/Entity.i"
	@echo "... OpenGLClasses/Entity.s"
	@echo "... OpenGLClasses/LightSource.o"
	@echo "... OpenGLClasses/LightSource.i"
	@echo "... OpenGLClasses/LightSource.s"
	@echo "... OpenGLClasses/RawModel.o"
	@echo "... OpenGLClasses/RawModel.i"
	@echo "... OpenGLClasses/RawModel.s"
	@echo "... OpenGLClasses/Shader.o"
	@echo "... OpenGLClasses/Shader.i"
	@echo "... OpenGLClasses/Shader.s"
	@echo "... OpenGLClasses/ShaderManager.o"
	@echo "... OpenGLClasses/ShaderManager.i"
	@echo "... OpenGLClasses/ShaderManager.s"
	@echo "... OpenGLClasses/Texture.o"
	@echo "... OpenGLClasses/Texture.i"
	@echo "... OpenGLClasses/Texture.s"
	@echo "... OpenGLClasses/TexturedModel.o"
	@echo "... OpenGLClasses/TexturedModel.i"
	@echo "... OpenGLClasses/TexturedModel.s"
	@echo "... OpenGLClasses/Vertex.o"
	@echo "... OpenGLClasses/Vertex.i"
	@echo "... OpenGLClasses/Vertex.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... obj_parser.o"
	@echo "... obj_parser.i"
	@echo "... obj_parser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

